### ISSUE TITLE
lace public repo

### ISSUE THREAD

**Issue by duncdrum** [brobertson/Lace2#124]
`http://heml.ddns.net:8080/exist/apps/public-repo/` seems either down or not publicly accessible, since installing the app makes this the default app repo for packagemanager this is a bit unfortunate. 

the switch should be documented so users are aware what's happening, and in a future update maybe we can get this to work  more elegantly so that users still get their regular app updates from exist-db's default public repo.

see eXist-db/existdb-packageservice#16

**Comment by brobertson** [comment]
Thanks. I don't consider this feature as useful as did in the past, especially since one makes the eXist repo unuseable. So my current testing code does not use a repo, and the plan is for users just to download from a website. The downside of this is that the package dependency of images and texts can't be automatically resolved, but it's not too much to ask that people install two packages, and I've found that in general package management has fallen on my shoulders for our project, not on individual users.

**Comment by duncdrum** [comment]
@brobertson i think the feature could be very useful. Not just for this app. So in light of this, I would slightly modify the `replace` statement in your `preinstall.xq` to `insert` And see that we can fix the problem upstream so that specifying multiple repos, will actually show packages from both.

**Comment by brobertson** [comment]
Nice idea. Thanks.

**Comment by duncdrum** [comment]
@brobertson the PR is here https://github.com/eXist-db/existdb-packageservice/pull/17 I ll incorporate the necessary updates into my fork.
